// Local-only demo: no OAuth, no external API calls, no external writes.
// Signals are fictional. Nothing is sent, changed, or executed.

function main(): void {
  console.log('');
  console.log('WorldLoops found 6 unfinished responsibilities across your day.');
  console.log('');
  console.log('Sources:');
  console.log('- Email');
  console.log('- Calendar');
  console.log('- Chat');
  console.log('- Document');
  console.log('- Project tool');
  console.log('- Meeting note');
  console.log('');
  console.log('─────────────────────────────────────────────────────────────────');
  console.log('Open Loops:');
  console.log('─────────────────────────────────────────────────────────────────');
  console.log('');
  console.log('1. Proposal follow-up');
  console.log('   Source: Email');
  console.log('   State: To Do');
  console.log('   Why it matters: David asked for a proposal by Friday.');
  console.log('   Suggested next step: Prepare or draft the proposal follow-up.');
  console.log('   Safety: WorldLoops did not send an email.');
  console.log('');
  console.log('2. Workshop preparation');
  console.log('   Source: Calendar');
  console.log('   State: Preparing');
  console.log('   Why it matters: A workshop is scheduled and materials are required.');
  console.log('   Missing items:');
  console.log('   - Final presentation materials');
  console.log('   - Workshop canvas');
  console.log('   Safety: WorldLoops did not edit your calendar.');
  console.log('');
  console.log('3. Pricing plan review');
  console.log('   Source: Chat');
  console.log('   State: To Do');
  console.log('   Why it matters: The request is time-sensitive.');
  console.log('   Suggested next step: Review the pricing plan or assign an owner.');
  console.log('   Safety: WorldLoops did not post a reply.');
  console.log('');
  console.log('4. Missing ROI assumptions');
  console.log('   Source: Document');
  console.log('   State: Blocked');
  console.log('   Why it matters: The proposal still has an unfinished TODO.');
  console.log('   Suggested next step: Add ROI assumptions before sending.');
  console.log('   Safety: WorldLoops did not modify the document.');
  console.log('');
  console.log('5. Approval needed before release');
  console.log('   Source: Project tool');
  console.log('   State: Waiting for review');
  console.log('   Why it matters: A change is ready, but someone needs to review it before release.');
  console.log('   Suggested next step: Review or approve the change.');
  console.log('   Safety: WorldLoops did not merge, approve, or change anything.');
  console.log('');
  console.log('6. Customer follow-up');
  console.log('   Source: Meeting note');
  console.log('   State: To Do');
  console.log('   Why it matters: Sarah needs a follow-up after the demo.');
  console.log('   Suggested next step: Draft a follow-up message with next steps.');
  console.log('   Safety: WorldLoops did not contact Sarah.');
  console.log('');
  console.log('─────────────────────────────────────────────────────────────────');
  console.log('Summary:');
  console.log('6 open loops found');
  console.log('0 emails sent');
  console.log('0 calendar events changed');
  console.log('0 chat messages posted');
  console.log('0 files modified');
  console.log('0 project changes made');
  console.log('');
  console.log('Everything is local.');
  console.log('Everything is reviewable.');
  console.log('Nothing executes without approval.');
  console.log('');
}

main();
